openapi: 3.0.0
info:
  title: txn-definition
  description: txn-definition API
  version: '1.0'
  contact:
    name: Anjali Israni
    email: anjali.israni@sage.com
servers:
  - url: http://localhost:3000
tags:
  - name: Transaction definition
    description: Transaction definition description.
paths:
  /objects/txn-definition:
    get:
      summary: List transaction definition
      description: Returns a collection with a key, ID, and link for each transaction definition.
      tags:
        - Transaction definition
      operationId: get-objects-txn-definition
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of txn-definition objects
                properties:
                  ia::result:
                    type: array
                    items:
                      $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata-pages.schema'
              examples:
                example-1:
                  value:
                    ia::result:
                      - key: '33'
                        id: '33'
                        href: /objects/txn-definition/33
                    ia::meta:
                      totalCount: 1
                      start: 1
                      pageSize: 100
                      next: null
                      previous: null
        '400':
          $ref: '#/components/responses/400error'
    post:
      summary: Create a/an transaction definition
      description: Creates a new transaction definition.
      tags:
        - Transaction definition
      operationId: post-objects-txn-definition
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/txn-definition.s1.schema'
                - $ref: '#/components/schemas/txn-definitionRequiredProperties'
            examples:
              example-1:
                value:
                  id: Sales Invoice
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                title: New txn-definition
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples: {}
        '400':
          $ref: '#/components/responses/400error'
  /objects/txn-definition/{key}:
    parameters:
      - name: key
        description: System-assigned key for the transaction definition.
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a transaction definition
      description: Returns detailed information for a particular transaction definition.
      tags:
        - Transaction definition
      operationId: get-objects-txn-definition-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the txn-definition
                properties:
                  ia::result:
                    $ref: '#/components/schemas/txn-definition.s1.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                example-1:
                  value:
                    ia::result:
                      key: '154'
                      id: Sales Invoice
                      href: /objects/txn-definition/154
                    ia::meta:
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
    patch:
      summary: Update a/an transaction definition
      description: Updates an existing transaction definition by setting field values. Any fields not provided remain unchanged.
      tags:
        - Transaction definition
      operationId: patch-objects-txn-definition-key
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/txn-definition.s1.schema'
                - type: object
                  properties:
                    id:
                      readOnly: true
                      example: 'true'
            examples:
              example-1:
                value:
                  key: '154'
                  id: 'true'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated txn-definition
                properties:
                  ia::result:
                    $ref: '#/components/schemas/object-reference.schema'
                  ia::meta:
                    $ref: '#/components/schemas/metadata.schema'
              examples:
                example-1:
                  value:
                    ia::result:
                      key: '33'
                      id: '33'
                      href: /objects/txn-definition/33
                    ia::meta:
                      totalCount: 1
        '400':
          $ref: '#/components/responses/400error'
    delete:
      summary: Delete a/an transaction definition
      description: Deletes a/an transaction definition.
      tags:
        - Transaction definition
      operationId: delete-objects-txn-definition-key
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/400error'
components:
  schemas:
    txn-definition:
      $ref: '#/components/schemas/txn-definition.s1.schema'
    txn-definitionRequiredProperties:
      type: object
      required:
        - id
    object-reference.schema:
      title: object-reference
      type: object
      description: Reference Object definition
      properties:
        key:
          type: string
        id:
          type: string
        href:
          type: string
          readOnly: true
    metadata.schema:
      title: metadata
      description: Meta data for response
      type: object
      properties:
        totalCount:
          type: integer
          description: Total Count
          readOnly: true
          example: 3
    metadata-pages.schema:
      title: metadata-pages
      description: Meta data for collection response
      type: object
      allOf:
        - $ref: '#/components/schemas/metadata.schema'
        - type: object
          properties:
            start:
              type: integer
              description: Start Element Number
              x-mappedTo: null
              readOnly: true
              example: 1
            pageSize:
              type: integer
              description: Page Size
              x-mappedTo: null
              readOnly: true
              example: 100
            next:
              type: integer
              description: Next Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: 101
            previous:
              type: integer
              description: Previous Element Number
              x-mappedTo: null
              readOnly: true
              nullable: true
              example: null
    error-response.schema:
      title: error-response
      type: object
      description: Error response
      properties:
        ia::error:
          type: object
          properties:
            code:
              type: string
              example: invalidRequest
            message:
              type: string
              example: Malformed URL
            supportId:
              type: string
              example: sQrM9%7EYdh5oDEWVb80mrn9xuHjoAAAABBQ
            details:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                    example: TODO
                  message:
                    type: string
                    example: TODO
                  correction:
                    type: string
                    example: TODO
    txn-definition.s1.schema:
      title: txn-definition
      type: object
      description: Transaction definition
      x-mappedTo: documentparams
      properties:
        key:
          type: string
          description: key
          x-mappedTo: RECORDNO
          readOnly: true
          example: '154'
        id:
          type: string
          description: id
          x-mappedTo: DOCID
          x-mutable: false
          example: Sales Invoice
        href:
          type: string
          readOnly: true
          example: /objects/txn-definition/154
  responses:
    400error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error-response.schema'
