openapi: 3.0.0
info:
  title: contract-expense-schedule
  description: contract-expense-schedule API
  version: '1.0'
  contact:
    name: Jim Reed
    email: jim.reed@sage.com
tags:
  - name: Contract expense schedules
    description: A contract expense schedule is a header containing multiple schedule lines and is tied directly to a contract line.
servers:
  - url: 'http://localhost:3000'
paths:
  /objects/contract-expense-schedule:
    get:
      summary: List contract expense schedules
      description: 'Returns a collection with a key, ID, and link for each contract-expense-schedule.'
      tags:
        - Contract expense schedules
      operationId: get-objects-contract-expense-schedule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: List of contract expense schedule objects
                properties:
                  'ia::result':
                    type: array
                    items:
                      $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-pages.schema.yaml
              examples:
                List of contract expense schedules:
                  value:
                    'ia::result':
                      - key: '84'
                        id: RT-00001
                        href: /objects/contract-expense-schedule/84
                      - key: '85'
                        id: RT-00002
                        href: /objects/contract-expense-schedule/85
                      - key: '60'
                        id: RT-00003
                        href: /objects/contract-expense-schedule/60
                      - key: '78'
                        id: RT-00004
                        href: /objects/contract-expense-schedule/78
                      - key: '79'
                        id: RT-00005
                        href: /objects/contract-expense-schedule/79
                    'ia::meta':
                      totalCount: 5
                      start: 1
                      pageSize: 100
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  'ia::result':
                    $ref: ../../common/models/error-response.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-extended.schema.yaml
              examples:
                List of contract expense schedule errors:
                  value:
                    'ia::result':
                      'ia::error':
                        code: invalidRequest
                        message: 'Object named [contract-expense-schedule] is not supported in version [0]'
                        supportId: '-hOIM%7EYagYsDEpVbp0kVn1KUJ45gAAAAQ'
                    'ia::meta':
                      totalCount: 1
                      totalSuccess: 0
                      totalError: 1
  '/objects/contract-expense-schedule/{key}':
    parameters:
      - name: key
        description: System-assigned key for the contract expense schedule.
        in: path
        required: true
        schema:
          type: string
          example: '762'
    get:
      summary: Get a contract expense schedule
      description: Returns detailed information for a particular contract expense schedule.
      tags:
        - Contract expense schedules
      operationId: get-objects-contract-expense-schedule-key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Details of the contract expense schedule
                properties:
                  'ia::result':
                    $ref: '#/components/schemas/contract-expense-schedule'
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  href:
                    type: string
                  'ia::result':
                    $ref: ../../common/models/error-response.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-extended.schema.yaml
              examples:
                Update a contract expense schedule error:
                  value:
                    key: '12'
                    href: /objects/contract-expense-schedule/12
                    'ia::result':
                      'ia::error':
                        code: invalidRequest
                        message: 'Field [id] is a read-only field'
                        supportId: YCbdS%7EYagQGDEvVbn0UIY1o-JKOAAAAAo
                    'ia::meta':
                      totalCount: 1
                      totalSuccess: 0
                      totalError: 1
    patch:
      summary: Update a contract expense schedule
      description: Updates an existing contract expense schedule by setting field values. Any fields not provided remain unchanged.
      tags:
        - Contract expense schedules
      operationId: patch-objects-contract-expense-schedule-key
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contract-expense-schedule'
            examples:
              Add a expense schedule line:
                value:
                  key: '145'
                  expenseScheduleLines:
                    - scheduledExpenseDate: '2022-05-25'
                      scheduledAmount: '125.34'
              Update a expense schedule line:
                value:
                  key: '145'
                  expenseScheduleLines:
                    - key: '12'
                      scheduledExpenseDate: '2022-05-25'
                      scheduledAmount: '125.34'
              Update a multiple expense schedule line:
                value:
                  key: '145'
                  expenseScheduleLines:
                    - key: '12'
                      scheduledExpenseDate: '2022-05-25'
                      scheduledAmount: '125.34'
                    - key: '13'
                      scheduledExpenseDate: '2022-06-25'
                      scheduledAmount: '245.18'
              Delete a expense schedule line:
                value:
                  key: '145'
                  expenseScheduleLines:
                    - 'ia::operation': delete
                      key: '12'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: Updated contract expense schedule
                properties:
                  'ia::result':
                    $ref: ../../common/models/object-reference.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata.schema.yaml
              examples:
                Update a contract expense schedule:
                  value:
                    'ia::result':
                      key: '12'
                      id: 2021-LV2
                      href: /objects/contract-expense-schedule/12
                    'ia::meta':
                      totalCount: 1
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  href:
                    type: string
                  'ia::result':
                    $ref: ../../common/models/error-response.schema.yaml
                  'ia::meta':
                    $ref: ../../common/models/metadata-extended.schema.yaml
              examples:
                Update a contract expense schedule error:
                  value:
                    key: '145'
                    href: /objects/contract-expense-schedule/145
                    'ia::result':
                      'ia::error':
                        code: notFound
                        message: 'The requested resource [contract-expense-schedule] with key(s) [145] could not be found but may be available in the future'
                        supportId: PhOIM%7EYagW2DEpVbp0kVn1KUJ43wAAAAQ
                    'ia::meta':
                      totalCount: 1
                      totalSuccess: 0
                      totalError: 1
components:
  schemas:
    contract-expense-schedule:
      type: object
      allOf:
        - $ref: ../models/contract-expense-schedule.s1.schema.yaml
        - $ref: ../references/contract-schedule-typeref.s1.schema.yaml
